#!/usr/bin/python3
#coding=utf-8

import os,urllib3


ip1=120

ip2=24

ip3=243

ip4=133

ip=str(ip1)+'.'+str(ip2)+'.'+str(ip3)+'.'+str(ip4)

url='http://ip.chinaz.com/?IP='+ip

http=urllib3.PoolManager()

html=http.request('GET',url)


print(html.data.decode('utf-8'))


print('汉字~~~~~')
