#!/usr/bin/env python3
#coding=utf-8

import sys,socket,os

BUF=4096

def info(data):
	l=data.split(',')
	l[1]=int(l[1])
	return l[0],l[1]

ADDR=('0.0.0.0',6789)
S=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)

S.bind(ADDR)

data,address = S.recvfrom(BUF)

data=data.decode('utf-8')

filename,filesize = info(data)

S.sendto('OK!'.encode('utf-8'),address)

f=open(filename,'wb')



while filesize > 0:
	if filesize > BUF:
		data,address = S.recvfrom(BUF)
		filesize-=BUF
		f.write(data)
	else:
		data,address = S.recvfrom(BUF)
		filesize-=len(data)
		f.write(data)

f.close()
print('接收完成。')
S.close()
