#!/usr/bin/python3
#coding=utf-8


ip1=1;ip2=1;ip3=1;ip4=1

ip1=192;ip2=15;

while ip1<=254:
	if ip1==10 or ip1==127 or ip1==192: 
		ip1+=1
		continue
	while ip2<=254:
		if 16<=ip2<=32 or ip2==168:
			ip2+=1
			continue
		while ip3<=254:
			while ip4<=254:
				ipsearchaddr=str(ip1)+'.'+str(ip2)+'.'+str(ip3)+'.'+str(ip4)
				print(ipsearchaddr)
				
				ip4+=1
			ip3+=1
			ip4=1
		ip2+=1
		ip3=1
	ip1+=1
	ip2=1

