#!/usr/bin/env python3
#coding=utf-8


import sys,getopt

try:
		opts,args = getopt.getopt(sys.argv[1:],"htop::",["help","print=="])
except getopt.GetoptError as e:
		print("getopt error....",e)
		sys.exit(1)


print(opts,args,sep='\n')


for opt ,arg  in opts:
		if opt in ('-h','--help'):
				print("Usage: {} -h".format(sys.argv[0]))
		elif opt in ('-p',"--print"):
				print('print :',arg,args)
		elif opt in ('-to'):
				print('-to OK!')

