#!/usr/bin/env python3
#coding=utf-8

import argparse

parse = argparse.ArgumentParser(
description='Process some integers.',
add_help=True) 

parse.add_argument('--int', metavar='N', type=int, nargs='+', help='an integer for the accumulator') 

parse.add_argument('--sum',action='store_const', const=sum, default=max, help='sum the integers (default: find the max)') 

#parse.add_argument('-f', metavar='F',nargs='+', help='an integer for the accumulator') 

parse.add_argument('-c',action='append_const',const=int,help='nothing')
parse.add_argument('--const',action='store_const',const='string',help='Nothing')
args = parse.parse_args() 

print(args)

