#!/usr/bin/env python3
#coding=utf-8


import poplib

host='pop.qq.com'

username='1041878651@qq.com'

password='my@python$smtp'

pop=poplib.POP3(host)

pop.set_debuglevel(1)

pop.user(username)

pop.pass_(password)

ret=pop.stat()

print(ret)

for i in range(1,ret[0]+1):
		mlist=pop.top(i,0)
		print('lines: ',len(mlist[1]))

ret= pop.list()
print(ret)

donw = pop.retr(1)

print('lines: ',len(down))

for line in down[1]:
		print(line)


pop.quit()
