#!/usr/bin/env python3 
#coding=utf-8

import socket,time

buf=1024
try:
		Server=socket.socket(socket.AF_INET,socket.SOCK_STREAM)

		Server.bind(('127.0.0.1',12345))

		Server.listen(5)

except:
		print('have Exception.')
		raise
else:
		print('Server listen() init done.')



try:
		s,address = Server.accept()

		print('客户端地址 ：{}'.format(address))

		data=s.recv(buf)
		if not data:
				print('recv() error.')
		d='recv: ' + data.decode('utf-8')
		print(d)

		s.send('服务器的发送。'.encode('utf-8'))

except:
		print('recv(),send() Exception ')
		raise
finally:
		Server.close()
		s.close()





