#!/usr/bin/env python3
#coding=utf-8

import time;

localtime=time.localtime(time.time())

print("now is time :",localtime)


localtime=time.asctime(time.localtime(time.time()))
print("fromat time :",localtime)


time.sleep(30)


print('Quit .')
