#!/usr/bin/env python3
#coding=utf-8

from tkinter import * 


root = Tk() 

 

def callback(): 

    print("called the callback!")


# create a toolbar 

toolbar = Frame(root) 

b = Button(toolbar, text="new", width=6, command=callback) 

b.pack(side=RIGHT, padx=0, pady=0) 

b = Button(toolbar, text="open", width=6, command=callback) 

b.pack(side=LEFT, padx=2, pady=2) 

toolbar.pack(side=TOP, fill=X) 


mainloop()
