#!/usr/bin/env python3
#coding=utf-8

import sys
import fileinput
from argparse import ArgumentParser

parser = ArgumentParser()
#parser.add_argument('--dummy', help='dummy argument')
parser.add_argument('files', metavar='FILE', nargs='*', help='files to read, if empty, stdin is used')
args = parser.parse_args()

char = 0
word = 0
lines = 0

# If you would call fileinput.input() without files it would try to process all arguments.
# We pass '-' as only file when argparse got no files which will cause fileinput to read from stdin
for line in fileinput.input(files=args.files if len(args.files) > 0 else ('-', ),mode='rb'):
	char += len(line)
	word += len(line.split())
	lines += 1
	#print(line)
	#input(r'enter continue > ')
print(lines,word,char,sep='\t')

