#!/usr/bin/python3
#coding=utf-8

testfile="testfile"

f=open(testfile,"w")

en=input("enter a string:")

f.write(en)

f.writelines("over  :::")

f.close()


f2=open(testfile,"r")

for line in f2:
    print("LLL  ",line)

f2.close()
