#!/usr/bin/env python3
#coding=utf-8


import hashlib,argparse


parse=argparse.ArgumentParser(description='md5sum')

parse.add_argument('files',nargs="+",help='files')

args=parse.parse_args()


md5 = hashlib.md5()
for f in args.files:

	fp=open(f,'rb')

	while True:

		data = fp.read(4096)

		if len(data) < 4096:
			md5.update(data)
			break
		else:
			md5.update(data)

	fp.close()

	print(f,md5.hexdigest(),sep='\t')
