
BEGIN; -- 开启事务，确保数据安全

-- 1. (可选但推荐) 如果有外键引用该主键，先删除外键约束
-- ALTER TABLE other_table DROP CONSTRAINT other_table_user_id_fkey;

-- 2. 删除旧的 SERIAL 列
-- 注意：这会同时删除该列依赖的自动创建的序列对象
ALTER TABLE zx DROP COLUMN id;

-- 3. 添加新的 IDENTITY 列
-- GENERATED BY DEFAULT: 允许手动插入指定ID (类似 SERIAL 的行为)
-- GENERATED ALWAYS: 强制系统生成，禁止手动插入 (更严格)
ALTER TABLE zx
ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- 4. (可选) 如果之前有外键，重新创建外键约束
-- ALTER TABLE other_table ADD CONSTRAINT other_table_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

COMMIT; -- 提交事务

