versions: "3"

services:
  pgsql1:
    #image: docker.io/library/postgres:17
    image: localhost/pgsql:17
    container_name: pgsql1
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: zx,pgsql
      POSTGRES_INITDB_ARGS: "--locale=zh_CN.UTF-8 --encoding=UTF-8"
      #LANG: zh_CN.UTF-8
    volumes:
      - ${HOME}/.volumes/postgresql:/var/lib/postgresql/data

        #  adminer:
        #    image: docker.io/library/adminer:latest
        #    restart: always
        #    networks:
        #      - postgres
        #    ports:
        #      - 8080:8080


networks:
  postgres:
    driver: bridge
  
