#!/usr/bin/env python3
#coding=utf-8

import socket as st
import time

BIND=('0.0.0.0',6789)
try:

		S=st.socket(st.AF_INET,st.SOCK_DGRAM)

		S.bind(BIND)

except:
		print('初始化异常！')
		raise

try:
		while 1:

			S.settimeout(5)
			data,address=S.recvfrom(8)
			data2=data.decode('utf-8')
			if data2=='quitserver':
				break
			#if data2.split(' ').[0] == 'address :':
			# data2.
			data='recv: '+data.decode('utf-8')
			print(time.ctime(),'address : ',address,data)
			S.sendto('OK!'.encode('utf-8'),address)
			print('sendto : OK done.')

except:
		print('recv : Exception')
		raise

finally:
		S.close()



