
[ext]
check_timeout = 5
check_failed_count = 6
server_hub = true

[ifname]
interface = "wg-pyz"
private_key = "private key"
address = ["10.1.3.200/24", "fc03::200/64"]
listen_port = 18000
MTU = 1280

[[peers]]
[peers.info]
comment = "这是peer端的备注"
wg_check_ip = "fc03::1"

[peers.peer]
public_key = "public key"
endpoint_addr = "ip or domainname"
endpoint_port = 18000
allowed_ips = ["10.1.3.0/24", "fc03::/64"]


[[peers]]
[peers.info]
comment = "这是peer2端的备注"
wg_check_ip = "fc03::1"

[peers.peer]
public_key = "public key"
endpoint_addr = "ip or domainname"
endpoint_port = 18000
allowed_ips = ["10.1.3.0/24", "fc03::/64"]