#!/usr/bin/env python3

import socket,sys

print(type(sys.argv),sys.argv)


s=socket.socket(socket.AF_INET,socket.SOCK_RAW,98)

if sys.argv[2]:
	data=sys.argv[2]

else:
	data='hello world!'

if sys.argv[1]:
	ip=sys.argv[1]

else:
	ip='127.0.0.1'

print('\ndata: ',data,'ip :',ip)
s.sendto(bytes(data,'ascii'),(ip,0))

