#!/usr/bin/env python3
#coding=utf-8

import sqlite3,readline,sys



db=sqlite3.connect(sys.argv[1])
cur=db.cursor()


try:
	while 1:
		try:
			cmd=input("sqlite3>")
		if cmd =='exit' or cmd == 'quit' or cmd == 'bye':
			raise KeyboardInterrupt
		fetch=cur.execute(cmd)
		except EOFError:
		exit(0)	
		except sqlite3.OperationalError as e:
			print(e)
			continue
		for f in fetch.fetchall():
			print(f)

except KeyboardInterrupt:
	exit(0)

finally:
	cur.close()
	db.close()

