#!/usr/bin/env python3
#coding=utf-8

import sqlite3,sys

try:
	import readline
except ImportError:
	print("realine 库不可用")


db=sqlite3.connect(sys.argv[1])
#cur=db.cursor()
cur=db


try:
	while True:
		try:
			cmd=input("sqlite3> ")
			if cmd =='exit' or cmd == 'quit' or cmd == 'bye':
				raise KeyboardInterrupt(cmd)
			fetch=cur.execute(cmd)
		except EOFError:
			exit(0)	
		except sqlite3.OperationalError as e:
			print(e)
			continue
		for f in fetch.fetchall():
			print(f)

except KeyboardInterrupt as e:
	print(e)
	exit(0)

finally:
	#cur.close()
	db.commit()
	db.close()

